services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    env_file:
      - ./.env
    environment:
      - MONGO_URI:"mongodb+srv://bodunrindavid:davidbond@cluster0.phiae.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - ADMIN_EMAIL:"admin@bct.com",
      - PORT:"5500"
    volumes:
      - .:/app
      - /app/node_modules
